### ISSUE TITLE
Add functionality to allow a user to remove a survey from the list of surveys if it has been deleted from Qualtrics

### ISSUE THREAD

**Issue by knkiers** [quantum-bits/capernaum#52]
Comment from Steve:

> The list of imported surveys in Cap seems to list a survey even after it is deleted at Qualtrics. Doesn't matter at this time but someday it would be nice to have the option to remove a survwy from that list. I don't want it to auto refresh because I might need to close a survey at Qual (make it non-active) and then later want to make it active again (so it would be nice to not have it auto-delete from the list in Cap and then need to recreate the whole letter, dimensions, indexes, table...

KK: Maybe this is a good place to use an "inactive" flag or something...?  Maybe the inactive flag could be set automatically if the survey at Qualtrics is deleted.

**Comment by nurkkala** [comment]
Added delete action for all survey responses.
